#!/bin/bash
set -e

pkcon install tlp -y
lsb_release -si | grep -qi "^Arch" && sudo pacman -S tlp-rdw --noconfirm
sudo systemctl enable tlp.service --now
sudo systemctl mask systemd-rfkill.{service,socket} --now
sudo tlp start

echo "$0" >>~/deployworkenv.log
