#!/bin/bash

cat <<END | sudo tee /etc/profile.d/fcitx5.sh >/dev/null
if [ ! "$XDG_SESSION_TYPE" = "tty" ]
then
    export INPUT_METHOD=fcitx
    export GTK_IM_MODULE=fcitx
    export QT_IM_MODULE=fcitx
    export XMODIFIERS=@im=fcitx
fi
END

read -p '立刻重启计算机以生效 (y/N)?' r
[[ "$r" =~ ^(Y|y)$ ]] && sudo reboot

echo "$0" >>~/deployworkenv.log
