#!/bin/bash

[[ ! -z "$(dconf read /org/gnome/desktop/input-sources/xkb-options)" ]] &&
    kwriteconfig5 --file ~/.config/fcitx5/conf/xcb.conf --group "<default>" --key 'Allow Overriding System XKB Settings' False

echo "$0" >> ~/deployworkenv.log

cat << END | dconf load /org/gnome/shell/extensions/kimpanel/
[/]
font='Noto Sans CJK SC 18'
vertical=true
END
gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell --method org.gnome.Shell.Extensions.InstallRemoteExtension kimpanel@kde.org
