#!/bin/bash

kwriteconfig5 --file fcitx5/config --group Behavior --key ShareInputState All

kwriteconfig5 --file fcitx5/conf/clipboard.conf --group TriggerKey --key 0 "Super+V"
[[ -x "$(command -v gsettings)" ]] &&
    gsettings set org.gnome.shell.keybindings toggle-message-tray "['<Super>m']"

kwriteconfig5 --file fcitx5/conf/pinyin.conf --group "<default>" --key PageSize 5
kwriteconfig5 --file fcitx5/conf/classicui.conf --group "<default>" --key "Vertical Candidate List" True
kwriteconfig5 --file fcitx5/conf/classicui.conf --group "<default>" --key Font "Noto Sans CJK SC 22"

echo "$0" >> ~/deployworkenv.log
