#!/bin/bash

kwriteconfig5 --file kwinrc --group Plugins --key kwin4_effect_dimscreenEnabled true

read -p '1. No prompt before power off (Y/n)? ' r
[[ "$r" =~ ^(Y|y|)$ ]] &&
    kwriteconfig5 --file ksmserverrc --group General --key confirmLogout false

read -p '2. Hide maximum window titlebar [ recovered by dragging or `Super + PageUp` ] (Y/n)? ' r
if [[ "$r" =~ ^(Y|y|)$ ]]; then
    kwriteconfig5 --file ~/.config/kwinrc --group Windows --key BorderlessMaximizedWindows true
    qdbus org.kde.KWin /KWin reconfigure
fi

read -p '3. Enable overview [ KDE >= 5.24, actived by `Super + W` ] (Y/n)? ' r
[[ "$r" =~ ^(Y|y|)$ ]] &&
    kwriteconfig5 --file kwinrc --group Plugins --key overviewEnabled true

echo ? "$0" >>~/deployworkenv.log
