#!/bin/bash
export NOLOG=1
DIR=$(dirname "$0")

RUNZSH=no \
    SCRIPTURL=https://gitee.com/mirrors/oh-my-zsh/raw/master/tools/install.sh \
    REMOTE=https://gitee.com/mirrors/oh-my-zsh.git \
    zsh/setup

echo '推荐的 .zshrc 配置：'
cat "$DIR/_recommend.zsh"
read -p '是否使用 (Y/n)? ' r
[[ "$r" =~ ^(Y|y|)$ ]] && cat "$DIR/_recommend.zsh" >>~/.zshrc

echo "$0" >>~/deployworkenv.log
