#!/bin/bash
source ./gnome/ext/_common.bash

cat << END | dconf load /org/gnome/shell/extensions/appindicator/
[/]
icon-size=24
tray-pos='left'
END
gnome-extensions list | grep -q 'ubuntu-appindicators@ubuntu.com' ||
gnome_install_extension 'appindicatorsupport@rgcjonas.gmail.com'

echo  ./gnome/ext/apptray >> ~/deployworkenv.log
