#!/bin/bash
source ./gnome/ext/_common.bash

dconf load /org/gnome/shell/extensions/nightthemeswitcher/ <<END
[time]
always-enable-ondemand=true
nightthemeswitcher-ondemand-keybinding=['']
END
gnome_install_extension 'nightthemeswitcher@romainvigier.fr'

echo  ./gnome/ext/autonight >> ~/deployworkenv.log
