#!/bin/bash
source "$(dirname $0)/_common.bash"

dconf load /org/gnome/shell/extensions/nightthemeswitcher/ <<END
[time]
always-enable-ondemand=true
nightthemeswitcher-ondemand-keybinding=['']
END
gnome-install-extension 'nightthemeswitcher@romainvigier.fr'

echo "$0" >> ~/deployworkenv.log
