#!/bin/bash
source ./gnome/ext/_common.bash

dconf load /org/gnome/shell/extensions/babar/ <<END
[/]
display-activities=true
display-app-grid=false
display-favorites=false
favorites-first=true
icon-size=38
reduce-padding=false
right-click=false
END
gnome_install_extension 'babar@fthx'

echo  ./gnome/ext/babar >> ~/deployworkenv.log
