#!/bin/bash
source "$(dirname $0)/_common.bash"

dconf load /org/gnome/shell/extensions/babar/ <<END
[/]
display-activities=true
display-app-grid=false
display-favorites=false
favorites-first=true
icon-size=38
reduce-padding=false
right-click=false
END
gnome-install-extension 'babar@fthx'

echo "$0" >> ~/deployworkenv.log
