#!/bin/bash
source ./gnome/ext/_common.bash

dconf write /org/gnome/shell/extensions/just-perfection/top-panel-position 1
dconf write /org/gnome/shell/extensions/just-perfection/notification-banner-position 4
dconf write /org/gnome/desktop/enable-hot-corners false
dconf write /org/gnome/shell/extensions/dash-to-dock/show-apps-at-top true
dconf write /org/gnome/shell/extensions/custom-hot-corners-extended/monitor-0-bottom-left-0/action "'toggle-overview'"
dconf write /org/gnome/shell/extensions/custom-hot-corners-extended/monitor-0-bottom-right-0/action "'open-panel-aggregate-menu'"

$UUID1=dash-to-dock@micxgx.gmail.com
gnome-extensions list | grep -q $UUID1 || gnome_install_extension $UUID1

read -p "use Custom Hot Corners Extended (y/N)?" r
[[ "$r" =~ ^(y|Y)$ ]] &&
gnome_install_extension custom-hot-corners-extended@G-dH.github.com

echo '?' ./gnome/ext/bottompanel >> ~/deployworkenv.log
