#!/bin/bash
source "$(dirname $0)/_common.bash"

dconf load /org/gnome/shell/extensions/dash-to-dock/ <<END
[/]
multi-monitor=true
isolate-workspaces=true
isolate-monitors=true
show-trash=false
scroll-action='cycle-windows'
middle-click-action='quit'
click-action='focus-minimize-or-previews'
END
gnome-install-extension 'dash-to-dock@micxgx.gmail.com'

echo "$0" >> ~/deployworkenv.log
