#!/bin/bash
source ./gnome/ext/_common.bash

UUID=places-menu@gnome-shell-extensions.gcampax.github.com
gnome-extensions enable $UUID ||
gnome_install_extension $UUID

echo  ./gnome/ext/showplaces >> ~/deployworkenv.log
