#!/bin/bash
source "$(dirname $0)/_common.bash"

UUID=user-theme@gnome-shell-extensions.gcampax.github.com
gnome-extensions enable $UUID || gnome-install-extension $UUID

echo "$0" >> ~/deployworkenv.log
