#!/bin/bash
cat << END | dconf load /org/workrave/timers/
[micro-pause]
auto-reset=12
limit=1200
snooze=120
[rest-break]
auto-reset=480
limit=2400
snooze=300
END

cat << END | dconf load /org/workrave/gui/breaks/rest-break/
[/]
auto-natural=true
exercises=4
END

dconf write /org/workrave/breaks/daily-limit/enabled false
dconf write /org/workrave/gui/breaks/block-mode 0
dconf write /org/workrave/general/usage-mode 1

echo "$0" >> ~/deployworkenv.log
