#!/bin/bash
set -e
cd /etc/xdg/reflector
echo "-c cn" | tee -a reflector.conf &>/dev/null
sed -i -e '/^--ipv4$/d' -e '/^--ipv6$/d' reflector.conf
systemctl restart reflector
sed -i '/^#Parall/ s/^#//' /etc/pacman.conf
pacman -Sy --noconfirm
