#!/bin/bash
sudo pacman -S firefox --noconfirm

mkdir -p ~/.local/share/applications
cd ~/.local/share/applications
cp /usr/share/applications/firefox.desktop firefox-wayland.desktop
sed -i -e 's/^Name=Firefox$/Name=Wayland Firefox/' -e 's/^Exec=/Exec=env MOZ_ENABLE_WAYLAND=1 /' firefox-wayland.desktop
cd - >/dev/null

echo
echo 'Recommend Addons:'
echo '- Dark Reader'
echo '- decentraleyes'
echo '- uBlock Origin'
echo '- Tree Style Tab'
read -p 'Install them (Y/n)?' r
[[ "$r" =~ ^(Y|y|)$ ]] &&
    sudo pacman -S firefox-dark-reader firefox-decentraleyes firefox-ublock-origin firefox-tree-style-tab --noconfirm

echo ? "$0" >>~/deployworkenv.log
