#!/bin/bash
set -e
if [ -z "$DEVICE_FILE"]; then
    lsblk
    while :; do
        read -p 'block device name (/dev/?): ' DEVICE_NAME
        DEVICE_FILE="/dev/$DEVICE_NAME"
        if [ -b "$DEVICE_FILE" ]; then
            break
        else
            echo 'Invalid name!'
        fi
    done
fi

if [ -z "$NOENCRYPT" ]; then
    cryptsetup close cryptlvm &>/dev/null || :
    cryptsetup luksFormat -q "$DEVICE_FILE"
    printf "Again "
    cryptsetup open "$DEVICE_FILE" cryptlvm
    DEVICE_FILE=/dev/mapper/cryptlvm
fi
mkfs.btrfs "$DEVICE_FILE"

mkdir -p /mnt/btrfs
mount "$DEVICE_FILE" /mnt/btrfs
btrfs subvol create /mnt/btrfs/@
btrfs subvol create /mnt/btrfs/@home
umount /mnt/btrfs

mkdir -p /mnt/archinstall
mount -o relatime,compress=zstd:1,space_cache=v2,subvol=@ "$DEVICE_FILE" /mnt/archinstall
mkdir /mnt/archinstall/home
mount -o relatime,compress=zstd:1,space_cache=v2,subvol=@home "$DEVICE_FILE" /mnt/archinstall/home

mount | grep /mnt/archinstall
