#!/bin/bash
SCRIPTURL=${SCRIPTURL:-https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh}
ZPLGLIST=${ZPLG_LISTFILE:-$HOME/.zshrc.pluglist}
ZPLGLOADER=${ZPLG_LOADER:-$HOME/.zshrc.plugloader}

RUNZSH=no sh -c "$(wget -qO- "$SCRIPTURL")"
echo >>~/.zshrc

echo 'setopt beep nomatch notify' >>~/.zshrc

ZSH="${ZSH:-$HOME/.oh-my-zsh}"
ZSH_CUSTOM="$ZSH/custom"
DIR=$(dirname "$0")
TMPL_ZPLGLIST="$DIR/_omzpluglist"
TMPL_ZPLGLOADER="$DIR/_omzplugloader.zsh"

[[ -f "$ZPLGLIST" ]] || cat "$TMPL_ZPLGLIST" >"$ZPLGLIST"
[ -x "$(command -v systemctl)" ] && echo systemd >>"$ZPLGLIST"
[ -x "$(command -v dpkg)" ] && echo debian >>"$ZPLGLIST"
[ -x "$(command -v dnf)" ] && echo dnf >>"$ZPLGLIST"
[ -x "$(command -v lsb_release)" ] && lsb_release -si | grep -qi "^Arch" && echo archlinux >>"$ZPLGLIST"
[[ -f "$ZPLGLOADER" ]] || cat "$TMPL_ZPLGLOADER" >"$ZPLGLOADER"
sed -i "s#plugins=(git)\$#source \"$ZPLGLOADER\"#" ~/.zshrc

read -p 'Use ohmyzsh steeef theme (Y/n)? ' r
if [[ "$r" =~ ^(y|Y|)$ ]]; then
    cp $ZSH/themes/steeef.zsh-theme $ZSH_CUSTOM/themes
    sed -i -e '/^PROMPT=\$/i local exit_code="%(?,,C:%{$fg[red]%}%?%{$reset_color%})"' -e "/^PROMPT=\\$'$/{n;s/$/ [%*] \$exit_code/;}" $ZSH_CUSTOM/themes/steeef.zsh-theme
    sed -i 's/^ZSH_THEME=".*"/ZSH_THEME="steeef"/' ~/.zshrc
fi

echo >>~/.zshrc

[[ -v NOLOG_GETOMZ ]] || echo "$0" >>~/deployworkenv.log
